# Handler for reloading systemd and restarting the application
- name: Reload systemd and restart application
  ansible.builtin.systemd:
    daemon_reload: true
    name: portfolio_app
    state: restarted
