name: Ansible Linting and Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create VVVVault Password File
        run: echo "fake_password_for_linting" > .vault_pass
      - name: Install Ansible-Lint Utility
        run: |
          pip install ansible ansible-lint

      - name: Run Syntax and Quality Checks
        run: |
          ansible-lint deploy.yml provision.yml
